In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pathlib

# Path

In [7]:
PROJECT_ROOT = pathlib.Path.cwd()
NOTEBOOK_DIR = PROJECT_ROOT/'python'/'freightCollabLeuven'
AGG_METRIC_BASE_PATH = PROJECT_ROOT/'data'/'freightCollabLeuven15Receivers'/'clean'

In [8]:
AGG_METRIC_FILEPATH = AGG_METRIC_BASE_PATH / 'all_scenarios_metrics.csv.gz'

# Read data

In [10]:
agg_metrics_df = pd.read_csv(AGG_METRIC_FILEPATH, compression='gzip')
agg_metrics_df

,ring_level,direction,allocation_method,allocation_factor,penalty,instance,num_receivers,fleet_size,iter0_fleet_size,final_carrier_score,...,iter0_VKT_km,VTT_seconds,iter0_VTT_seconds,TKT_tonkm,iter0_TKT_tonkm,mean_receiver_dist_to_depot_euclidean_km,mean_receiver_dist_to_depot_network_km,clustering_index_euclidean_km,clustering_index_network_km,depot_to_network_center_euclidean_km
0,r0,NE,approx_shapley_mc,0.8,0.0003,0,15,2,2,822.784625,...,25.659736,21190.0,22302.0,24198.946619,18027.358948,0.468783,1.883890,0.192242,0.528353,0.255739
1,r0,NE,approx_shapley_mc,0.8,0.0003,1,15,2,2,841.818640,...,21.712036,20981.0,21597.0,24763.664434,17937.496331,0.612420,1.654723,0.239085,0.641987,0.255739
2,r0,NE,approx_shapley_mc,0.8,0.0008,0,15,2,2,840.296317,...,25.659736,21669.0,22302.0,34042.795088,18027.358948,0.468783,1.883890,0.192242,0.528353,0.255739
3,r0,NE,approx_shapley_mc,0.8,0.0008,1,15,2,2,823.919410,...,21.712036,21054.0,21597.0,25181.882467,17937.496331,0.612420,1.654723,0.239085,0.641987,0.255739
4,r0,NE,approx_shapley_mc,0.8,0.0014,0,15,2,2,772.768767,...,25.659736,21042.0,22302.0,21683.320056,18027.358948,0.468783,1.883890,0.192242,0.528353,0.255739
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1241,r9,SW,proportional,0.8,0.0008,0,15,2,2,768.693855,...,47.892707,22908.0,25875.0,43425.864838,39586.209477,2.864836,4.516734,0.192242,0.528353,2.557172
1242,r9,SW,proportional,0.8,0.0014,0,15,2,2,772.578312,...,47.892707,22908.0,25875.0,43425.864838,39586.209477,2.864836,4.516734,0.192242,0.528353,2.557172
1243,r9,SW,proportional,0.8,0.0028,0,15,2,2,769.834698,...,47.892707,22908.0,25875.0,43425.864838,39586.209477,2.864836,4.516734,0.192242,0.528353,2.557172
1244,r9,SW,proportional,0.8,0.0056,0,15,2,2,743.016387,...,47.892707,24962.0,25875.0,41249.746535,39586.209477,2.864836,4.516734,0.192242,0.528353,2.557172
1245,r9,SW,proportional,0.8,0.0098,0,15,2,2,717.099438,...,47.892707,25875.0,25875.0,39586.209477,39586.209477,2.864836,4.516734,0.192242,0.528353,2.557172

## Filter useful records for analysis

In [11]:
anls_agg_metrics_df = agg_metrics_df[agg_metrics_df['instance']==0]
anls_agg_metrics_df

,ring_level,direction,allocation_method,allocation_factor,penalty,instance,num_receivers,fleet_size,iter0_fleet_size,final_carrier_score,...,iter0_VKT_km,VTT_seconds,iter0_VTT_seconds,TKT_tonkm,iter0_TKT_tonkm,mean_receiver_dist_to_depot_euclidean_km,mean_receiver_dist_to_depot_network_km,clustering_index_euclidean_km,clustering_index_network_km,depot_to_network_center_euclidean_km
0,r0,NE,approx_shapley_mc,0.8,0.0003,0,15,2,2,822.784625,...,25.659736,21190.0,22302.0,24198.946619,18027.358948,0.468783,1.883890,0.192242,0.528353,0.255739
2,r0,NE,approx_shapley_mc,0.8,0.0008,0,15,2,2,840.296317,...,25.659736,21669.0,22302.0,34042.795088,18027.358948,0.468783,1.883890,0.192242,0.528353,0.255739
4,r0,NE,approx_shapley_mc,0.8,0.0014,0,15,2,2,772.768767,...,25.659736,21042.0,22302.0,21683.320056,18027.358948,0.468783,1.883890,0.192242,0.528353,0.255739
6,r0,NE,approx_shapley_mc,0.8,0.0028,0,15,2,2,785.973866,...,25.659736,21772.0,22302.0,25260.754733,18027.358948,0.468783,1.883890,0.192242,0.528353,0.255739
8,r0,NE,approx_shapley_mc,0.8,0.0056,0,15,2,2,801.937328,...,25.659736,22192.0,22302.0,26797.199089,18027.358948,0.468783,1.883890,0.192242,0.528353,0.255739
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1241,r9,SW,proportional,0.8,0.0008,0,15,2,2,768.693855,...,47.892707,22908.0,25875.0,43425.864838,39586.209477,2.864836,4.516734,0.192242,0.528353,2.557172
1242,r9,SW,proportional,0.8,0.0014,0,15,2,2,772.578312,...,47.892707,22908.0,25875.0,43425.864838,39586.209477,2.864836,4.516734,0.192242,0.528353,2.557172
1243,r9,SW,proportional,0.8,0.0028,0,15,2,2,769.834698,...,47.892707,22908.0,25875.0,43425.864838,39586.209477,2.864836,4.516734,0.192242,0.528353,2.557172
1244,r9,SW,proportional,0.8,0.0056,0,15,2,2,743.016387,...,47.892707,24962.0,25875.0,41249.746535,39586.209477,2.864836,4.516734,0.192242,0.528353,2.557172
1245,r9,SW,proportional,0.8,0.0098,0,15,2,2,717.099438,...,47.892707,25875.0,25875.0,39586.209477,39586.209477,2.864836,4.516734,0.192242,0.528353,2.557172